apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: myapp
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: myapp-issuer
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - __UAT_HOST__
      secretName: app-tls
  rules:
    - host: __UAT_HOST__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 5000
