apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp

resources:
  - namespace.yml
  - configmap.yml
  - secret.yml
  - pvc.yml
  - deployment-db.yml
  - service-db.yml
  - deployment-app.yml
  - service-app.yml
  - ingress.yml
