apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "myapp.name" . }}-db-data
  namespace: {{ .Release.Namespace }}
  labels: {{ include "myapp.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.storage }}
