apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myapp.name" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{ include "myapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASS: {{ .Values.db.password }}
  POSTGRES_PASSWORD: {{ .Values.db.password }}
